# Generated by Django 5.0.3 on 2024-03-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingListing",
            fields=[
                ("parking_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("spot_type", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=7)),
                ("features", models.TextField()),
                ("hourly", models.BooleanField(default=False)),
                ("daily", models.BooleanField(default=False)),
                ("maonthly", models.BooleanField(default=False)),
                ("price_hourly", models.DecimalField(decimal_places=2, max_digits=5)),
                ("price_daily", models.DecimalField(decimal_places=2, max_digits=5)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "parking_space_height",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "parking_space_width",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "parking_space_length",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "availability_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "parking_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.parkinglisting",
                    ),
                ),
            ],
        ),
    ]
