# Generated by Django 5.0.3 on 2024-03-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_parkinglisting_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkinglisting",
            old_name="maonthly",
            new_name="monthly",
        ),
        migrations.AlterField(
            model_name="parkinglisting",
            name="features",
            field=models.CharField(max_length=255),
        ),
    ]
