# Generated by Django 5.0.3 on 2024-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_rename_maonthly_parkinglisting_monthly_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="maonthly",
            field=models.BooleanField(default=False),
        ),
    ]
