# Generated by Django 5.0.3 on 2024-03-10 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_remove_userprofile_password_parkinglisting_maonthly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkinglisting",
            name="maonthly",
        ),
    ]
