# Generated by Django 5.0.3 on 2024-03-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_remove_parkinglisting_maonthly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("review", models.CharField(max_length=256)),
                (
                    "ParkingListing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="database.parkinglisting",
                    ),
                ),
            ],
        ),
    ]
