# Generated by Django 5.0.3 on 2024-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_rename_parkinglisting_reviews_parking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
