# Generated by Django 5.0.3 on 2024-03-12 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0010_reviews_user_id_alter_reviews_parking_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="user_id",
        ),
    ]
