# Generated by Django 5.0.3 on 2024-03-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0011_remove_reviews_rating_remove_reviews_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviews",
            name="user_id",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.userprofile",
            ),
            preserve_default=False,
        ),
    ]
