# Generated by Django 5.0.3 on 2024-03-12 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0012_reviews_rating_reviews_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
