# Generated by Django 5.0.3 on 2024-03-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0013_delete_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("review", models.CharField(max_length=256)),
                (
                    "parking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.parkinglisting",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.userprofile",
                    ),
                ),
            ],
        ),
    ]
