# Generated by Django 5.0.3 on 2024-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0015_alter_reviews_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
