# Generated by Django 5.0.3 on 2024-03-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0016_alter_reviews_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
