# Generated by Django 5.0.3 on 2024-03-13 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0018_banking_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availability",
            old_name="parking_listing",
            new_name="parking_id",
        ),
    ]
