# Generated by Django 5.0.3 on 2024-03-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0019_rename_parking_listing_availability_parking_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("sender", models.CharField(max_length=30)),
                ("receiver", models.CharField(max_length=30)),
                ("amount", models.SmallIntegerField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "Booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="database.booking",
                    ),
                ),
            ],
        ),
    ]
