# Generated by Django 5.0.3 on 2024-03-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='availability_id',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
