# Generated by Django 5.0.3 on 2024-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_booking_availability_id_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
