# Generated by Django 5.0.3 on 2024-03-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_booking_end_date_booking_end_time_booking_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
