# Generated by Django 5.0.3 on 2024-03-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_remove_booking_end_date_remove_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
