# Generated by Django 5.0.3 on 2024-03-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_booking_end_date_booking_end_time_booking_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parking_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.parkinglisting'),
            preserve_default=False,
        ),
    ]
