# Generated by Django 5.0.3 on 2024-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0025_booking_parking_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banking",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="favourite_location",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="parkinglisting",
            name="host",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="user_id",
        ),
        migrations.AddField(
            model_name="banking",
            name="user_email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="user_email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="favourite_location",
            name="user_email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="host_email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="reviews",
            name="user_email",
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
