# Generated by Django 5.0.3 on 2024-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0027_remove_parkinglisting_host_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglisting",
            name="host_email",
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
