# Generated by Django 5.0.3 on 2024-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0029_banking_card_holder_name_banking_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banking",
            name="card_holder_name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="banking",
            name="card_number",
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name="banking",
            name="cvv",
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name="banking",
            name="expiration_date",
            field=models.DateField(default=None),
        ),
    ]
