# Generated by Django 5.0.3 on 2024-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0031_parkinglisting_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarDetials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("nickname", models.CharField(max_length=20)),
                ("rego", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=20)),
            ],
        ),
    ]
