# Generated by Django 5.0.3 on 2024-03-21 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0032_cardetials"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardetials",
            old_name="type",
            new_name="vehicle_type",
        ),
    ]
