# Generated by Django 5.0.3 on 2024-03-24 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0033_rename_type_cardetials_vehicle_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banking",
            name="card_holder_name",
        ),
        migrations.RemoveField(
            model_name="banking",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="banking",
            name="cvv",
        ),
        migrations.RemoveField(
            model_name="banking",
            name="expiration_date",
        ),
    ]
