# Generated by Django 5.0.3 on 2024-03-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0034_remove_banking_card_holder_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(default=None, max_length=16)),
                ("card_holder_name", models.CharField(default=None, max_length=50)),
                ("expiration_date", models.DateField(default=None)),
                ("cvv", models.CharField(default=None, max_length=4)),
            ],
        ),
    ]
