# Generated by Django 5.0.3 on 2024-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0037_rename_cardetials_cardetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardetails",
            name="ev",
            field=models.BooleanField(default=False),
        ),
    ]
