# Generated by Django 5.0.3 on 2024-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0038_cardetails_ev"),
    ]

    operations = [
        migrations.AddField(
            model_name="banking",
            name="bsb",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
