# Generated by Django 5.0.3 on 2024-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0039_banking_bsb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banking",
            name="balance",
            field=models.SmallIntegerField(default=100),
        ),
    ]
