# Generated by Django 5.0.3 on 2024-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0040_alter_banking_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="carddetails",
            name="balance",
            field=models.SmallIntegerField(default=200),
        ),
    ]
