# Generated by Django 5.0.3 on 2024-03-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0041_carddetails_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglisting",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
