# Generated by Django 5.0.3 on 2024-03-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0042_parkinglisting_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
