# Generated by Django 5.0.3 on 2024-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0043_booking_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
