# Generated by Django 5.0.3 on 2024-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0044_alter_booking_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite_location",
            name="location",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
