# Generated by Django 5.0.3 on 2024-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0045_alter_favourite_location_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite_location",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="favourite_location",
            name="name",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
