# Generated by Django 5.0.3 on 2024-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0046_alter_favourite_location_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardetails",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
