# Generated by Django 5.0.3 on 2024-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0047_cardetails_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglisting",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AlterField(
            model_name="cardetails",
            name="nickname",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
