# Generated by Django 5.0.3 on 2024-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_cardetails_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
