# Generated by Django 5.0.3 on 2024-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0048_parkinglisting_latitude_parkinglisting_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglisting",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, default=None, max_digits=9, null=True
            ),
        ),
    ]
