# Generated by Django 5.0.3 on 2024-04-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0049_alter_parkinglisting_latitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglisting",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="parkinglisting",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
