# Generated by Django 5.0.3 on 2024-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0052_parkinglisting_latitude_parkinglisting_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardetails",
            name="nickname",
            field=models.CharField(max_length=20),
        ),
    ]
