# Generated by Django 5.0.3 on 2024-04-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0053_alter_cardetails_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardetails",
            name="nickname",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
