# Generated by Django 5.0.3 on 2024-04-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_alter_cardetails_nickname'),
        ('database', '0054_alter_cardetails_nickname'),
    ]

    operations = [
    ]
