# Generated by Django 5.0.3 on 2024-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0055_merge_20240401_2221"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite_location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="favourite_location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
