# Generated by Django 5.0.3 on 2024-04-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0056_favourite_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "parking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.parkinglisting",
                    ),
                ),
            ],
        ),
    ]
