# Generated by Django 5.0.3 on 2024-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0057_userprofile_disabled_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="parking_id",
            field=models.SmallIntegerField(),
        ),
    ]
