# Generated by Django 5.0.3 on 2024-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0058_alter_likes_parking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="banking",
            name="abn",
            field=models.IntegerField(default=0),
        ),
    ]
