# Generated by Django 5.0.3 on 2024-04-10 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0059_banking_abn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banking",
            name="abn",
        ),
    ]
