# Generated by Django 5.0.3 on 2024-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0060_remove_banking_abn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkinglisting",
            name="status",
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="reserved",
            field=models.BooleanField(default=False),
        ),
    ]
