# Generated by Django 5.0.3 on 2024-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0061_remove_parkinglisting_status_parkinglisting_reserved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="parkings")),
            ],
        ),
    ]
