# Generated by Django 5.0.3 on 2024-04-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0062_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="parkings")),
                (
                    "parking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.parkinglisting",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
