# Generated by Django 5.0.3 on 2024-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0063_parkingimages_delete_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("image", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="parkingimages",
            name="photo",
        ),
        migrations.AddField(
            model_name="parkingimages",
            name="image",
            field=models.TextField(default=None),
        ),
    ]
