# Generated by Django 5.0.3 on 2024-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0064_profilepicture_remove_parkingimages_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingimages",
            name="image",
            field=models.ImageField(upload_to="parking/"),
        ),
        migrations.AlterField(
            model_name="profilepicture",
            name="image",
            field=models.ImageField(upload_to="profile/"),
        ),
    ]
