# Generated by Django 5.0.3 on 2024-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_alter_parkingimages_image_alter_profilepicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglisting',
            name='status',
            field=models.CharField(default='private', max_length=7),
        ),
    ]
